* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Segoe UI', sans-serif;
  line-height: 1.6;
  background-color: #f9f9f9;
  color: #333;
}

.container {
  width: 90%;
  max-width: 1200px;
  margin: auto;
}

header {
  background: #222;
  color: #fff;
  padding: 1rem 0;
}

header h1 {
  float: left;
}

nav ul {
  float: right;
  list-style: none;
}

nav ul li {
  display: inline;
  margin-left: 20px;
}

nav ul li a {
  color: #fff;
  text-decoration: none;
}

.hero {
  background: linear-gradient(to right, #00b4db, #0083b0);
  color: #fff;
  text-align: center;
  padding: 5rem 1rem;
}

.hero .btn {
  display: inline-block;
  margin-top: 1rem;
  padding: 0.7rem 1.5rem;
  background: #fff;
  color: #0083b0;
  border-radius: 5px;
  text-decoration: none;
}

section {
  padding: 4rem 0;
}

.services ul {
  display: flex;
  gap: 20px;
  list-style: none;
  flex-wrap: wrap;
}

.services li {
  background: #fff;
  padding: 1rem;
  border-radius: 5px;
  flex: 1 1 200px;
  box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

form input, form textarea {
  padding: 0.75rem;
  border: 1px solid #ccc;
  border-radius: 5px;
}

form button {
  padding: 0.75rem;
  background: #0083b0;
  color: #fff;
  border: none;
  border-radius: 5px;
}

footer {
  background: #222;
  color: #fff;
  text-align: center;
  padding: 1rem 0;
  margin-top: 2rem;
}# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
